"""Inital Migration

Revision ID: 346572ad0c78
Revises: 
Create Date: 2023-05-25 12:35:16.711643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346572ad0c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hindalco_data',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('datetime_', sa.DateTime(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('open_', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hindalco_data')
    # ### end Alembic commands ###
